//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depending_parametres
    {
        public Nullable<long> reasonparam_id { get; set; }
        public Nullable<long> parameter_id { get; set; }
        public long id { get; set; }
    
        public virtual Parameters Parameters { get; set; }
        public virtual Reasons Reasons { get; set; }
    }
}
