//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emergency_situations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emergency_situations()
        {
            this.Reasons = new HashSet<Reasons>();
        }
    
        public long id { get; set; }
        public string number_st { get; set; }
        public string name_st { get; set; }
        public string place_st { get; set; }
        public Nullable<double> paramcritmin_re { get; set; }
        public Nullable<double> paramcritmax_re { get; set; }
        public Nullable<double> optimum_re { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reasons> Reasons { get; set; }
    }
}
