//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reasons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reasons()
        {
            this.Depending_parametres = new HashSet<Depending_parametres>();
            this.Recomendations = new HashSet<Recomendations>();
        }
    
        public long id { get; set; }
        public Nullable<long> ES_id { get; set; }
        public string text_st { get; set; }
        public Nullable<long> reasonnumber_in { get; set; }
        public string place_st { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Depending_parametres> Depending_parametres { get; set; }
        public virtual Emergency_situations Emergency_situations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendations> Recomendations { get; set; }
    }
}
