//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiningOffLine.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataMiningOffLine.Localization.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные отсутствуют..
        /// </summary>
        internal static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте технологические параметры в анализ!.
        /// </summary>
        internal static string AddParameter {
            get {
                return ResourceManager.GetString("AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показатель качества не изменяется. Выберите другой критерий разбиения.
        /// </summary>
        internal static string AnotherCriterion {
            get {
                return ResourceManager.GetString("AnotherCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднее.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные еще не собраны.
        /// </summary>
        internal static string DataNotGiven {
            get {
                return ResourceManager.GetString("DataNotGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  на 10 м².
        /// </summary>
        internal static string Defects {
            get {
                return ResourceManager.GetString("Defects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский перевод.
        /// </summary>
        internal static string EnName {
            get {
                return ResourceManager.GetString("EnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Н*м.
        /// </summary>
        internal static string ExtruderForce {
            get {
                return ResourceManager.GetString("ExtruderForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на об/мин.
        /// </summary>
        internal static string ExtruderVelocity {
            get {
                return ResourceManager.GetString("ExtruderVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не найден.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл с обученной моделью не найден. Сначала обучите модель..
        /// </summary>
        internal static string FileNotFoundMathematical {
            get {
                return ResourceManager.GetString("FileNotFoundMathematical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Н.
        /// </summary>
        internal static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытие формы.
        /// </summary>
        internal static string FormClosing {
            get {
                return ResourceManager.GetString("FormClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string IndexName {
            get {
                return ResourceManager.GetString("IndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обучение закончено.
        /// </summary>
        internal static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр №.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слишком много параметров выбрано. Количество параметров для каждой координаты должно быть не больше 10.
        /// </summary>
        internal static string ParametersSelected {
            get {
                return ResourceManager.GetString("ParametersSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не задали путь.
        /// </summary>
        internal static string PathWay {
            get {
                return ResourceManager.GetString("PathWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В выборке содержатся только показатели качества. Выберите технологические параметры..
        /// </summary>
        internal static string QualityParameters {
            get {
                return ResourceManager.GetString("QualityParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите сохранить изменения в базе данных?.
        /// </summary>
        internal static string QuestionSave {
            get {
                return ResourceManager.GetString("QuestionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В выборке содержатся только технологические параметры!.
        /// </summary>
        internal static string RegimeParameters {
            get {
                return ResourceManager.GetString("RegimeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бар.
        /// </summary>
        internal static string RollBending {
            get {
                return ResourceManager.GetString("RollBending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский перевод.
        /// </summary>
        internal static string RuName {
            get {
                return ResourceManager.GetString("RuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оригинальное название.
        /// </summary>
        internal static string ScadaName {
            get {
                return ResourceManager.GetString("ScadaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите показатель качества.
        /// </summary>
        internal static string SelectCriterion {
            get {
                return ResourceManager.GetString("SelectCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не выбрали ни одного параметра.
        /// </summary>
        internal static string SelectedParameters {
            get {
                return ResourceManager.GetString("SelectedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите критерий разбиения.
        /// </summary>
        internal static string SelectPartitioninCriterion {
            get {
                return ResourceManager.GetString("SelectPartitioninCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что-то не так.
        /// </summary>
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на °C.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные собраны за .
        /// </summary>
        internal static string TimeParameters {
            get {
                return ResourceManager.GetString("TimeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно обучить выборку..
        /// </summary>
        internal static string TrainSample {
            get {
                return ResourceManager.GetString("TrainSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Постройте дерево.
        /// </summary>
        internal static string TreeBuilding {
            get {
                return ResourceManager.GetString("TreeBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м/мин.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C дефектом.
        /// </summary>
        internal static string WithD {
            get {
                return ResourceManager.GetString("WithD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без дефекта.
        /// </summary>
        internal static string WithoutD {
            get {
                return ResourceManager.GetString("WithoutD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среди собранных параметров нету параметра дефекта. Соберите данные снова!.
        /// </summary>
        internal static string WithoutDefect {
            get {
                return ResourceManager.GetString("WithoutDefect", resourceCulture);
            }
        }
    }
}
